### ISSUE TITLE
Add TimeInstant metadata

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-thinking-things#26]
Add a TimeInstant metadata to every attribute, with the timestamp of the modification, as shown in the following example:
```
  {
            "id":"<entity-name>",
            "type" : "<entity-type>",
            "isPattern" : "false",
            "attributes" : [
                           {
             "name":"_TTcurrent_conf",
             "type":"string",
             "value":"44",
             "metadatas":[
                {
                 "name":"TimeInstant",
                 "type":"ISO8601",
                 "value":"2015-03-19T14:39:14.924961Z"
                }
                ]
            },
               {
             "name":"TimeInstant",
             "type":"ISO8601",
              "value":"2015-03-19T14:39:14.924961Z"
            }]
    }
```

**Comment by cbonillo** [comment]
If you resend the same data, a new notification is sent because the TimeInstant metadata has changed.
Is it possible to disable this feature?

**Comment by dmoranj** [comment]
You can disable the TimeInstant metadata as a whole, if that's what you wish, by setting the `ngsi.plain` configuration attribute to `false` (I think its the default value).

**Comment by cbonillo** [comment]
Should I edit my /etc/iot/config.json file?
I have not any ngsi.plain entry in my config.json. Where should I define this parameter?

**Comment by dmoranj** [comment]
I think we have a little misunderstanding here. This repository belongs to
the Node.js Thinking Things IoT Agent, and you seem to be using the CPP
version that can be found [here](
https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus). If that's the
case, I'm not sure that the timestamp insertion can be deactivated, please,
add an issue in that repository so the main developers can enter the
discussion.

As a matter of organization, please use issues to discuss bugs or requested
features, as commenting on a closed PR makes it difficult for the comment
to be found.

**Comment by cbonillo** [comment]
Sorry for the misunderstanding. 
I have registered an issue in IoTAgent-Cplusplus : https://github.com/telefonicaid/fiware-IoTAgent-Cplusplus/issues/246

Thank you for your quick reply.
